#!/bin/bash
cd /home/ec2-user/Foori

# 기존 파일 정리
rm -rf *

# 환경변수 파일 생성
cat << EOF > .env
VITE_KAKAO_MAP_KEY=${VITE_KAKAO_MAP_KEY}
VITE_TOSS_CLIENT_KEY=${VITE_TOSS_CLIENT_KEY}
VITE_BACK_URL=${VITE_BACK_URL}
VITE_REDIRECT_URL=${VITE_REDIRECT_URL}
VITE_SOCIAL_LOGIN_URL=${VITE_SOCIAL_LOGIN_URL}
VITE_SOCIAL_CONNECT_URL=${VITE_SOCIAL_CONNECT_URL}
EOF

npm install -g pm2
npm install